### ISSUE TITLE
Add `close()` method for cleaning up the discovery swarm

### ISSUE THREAD

**Issue by RangerMauve** [geut/discovery-swarm-webrtc#1]
Hi, I'm working on integrating this library with [dat-js](https://github.com/datproject/dat-js/pull/13).

I'm writing the tests for the cleanup behavior, and it would be nice if you had an easy way to `close` the swarm in the same vein as [discovery-swarm](https://github.com/mafintosh/discovery-swarm/blob/master/index.js#L71).

Would a PR with this support be welcome?

**Comment by dpaez** [comment]
Hi @RangerMauve 👋 Wow that sounds great and yeah a PR will be super welcome. 

Feel free to reach us if you need anything else. 👍

**Comment by RangerMauve** [comment]
Cool! I'll probably do one some time today. 😀

**Comment by tinchoz49** [comment]
closed by https://github.com/geut/discovery-swarm-webrtc/pull/2
