### ISSUE TITLE
Cannot be used in environments where `eval` is forbidden

### ISSUE THREAD

**Issue by sammacbeth** [geut/discovery-swarm-webrtc#11]
In applications where a [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) blocks `eval` this module cannot be imported. The cause is an upstream module in the `mostly-minimal-spanning-tree` dependency, and I opened an issue there: https://github.com/RangerMauve/mostly-minimal-spanning-tree/issues/2 . This issue is just to point out that upstream issue here.

This is currently blocking me trying out this module as Firefox webextensions are (rightly) always forbidden from doing `eval`.

**Comment by tinchoz49** [comment]
Hi @sammacbeth, this should be working now (with the last version of mmst). If is not re-open the issue :)
