### ISSUE TITLE
Example seems to not work in mac

### ISSUE THREAD

**Issue by tadli** [geut/discovery-swarm-webrtc#15]

**Comment by tinchoz49** [comment]
Try to provide a better description of the issue.

Which steps did you do?
Which error did you have?

**Comment by tinchoz49** [comment]
@dpaez can you try the example in your mac?

**Comment by dpaez** [comment]
`example` app is running fine on Mac OS. 

There is a `package.json` in the example folder, you should run `npm install` first and then `npm start`.
