### ISSUE TITLE
 to replicate or connect directly ?

### ISSUE THREAD

**Issue by sallespro** [geut/discovery-swarm-webrtc#20]
i am not sure how to use the Swarm connection to either replicate a hyperbee.
i undeerstood there are two ways, the simplePeer or to get the stream when one creates the swarm , is that it ?

my use case is i have a hyperbee in a client app and want to replicate elsewhere, with discovery-swarm-webrtc, instead of DHT for now.

what does this mean ? `We use behind it simple-signal + simple-peer. `

```
sw.connect(channel: Buffer, peerId: Buffer) -> Promise<SimplePeer>
Connect directly to a specific peer.
````

OR

```
{
  id: crypto.randomBytes(32), // peer-id for user
  bootstrap: [string], // urls to your websocket endpoints

  stream: (info) => stream, // stream to replicate across peers
...
}
```

**Comment by siuying** [comment]
I had the same question about `stream` parameter, should I just `(info) => feed.replicate(true)` to replicate a feed?

**Comment by sallespro** [comment]
the stream is a direct injection into simple-peer. No need to use it to replicate.
try something like below
```
feed.ready(() => {

  sw.on('connection', (conn, info) => {
    const protocol = feed.replicate(info.initiator, { live: true })
    pump(protocol, conn, protocol)
   
    })
  })
```

**Comment by sallespro** [comment]
a combined use of replicate & media stream
https://glitch.com/edit/#!/congruous-fire-shape?path=index.js%3A28%3A6

**Comment by siuying** [comment]
@sallespro thanks a lot for the example!
