### ISSUE TITLE
leave() method

### ISSUE THREAD

**Issue by RangerMauve** [geut/discovery-swarm-webrtc#3]
Hello! To follow up #1, I've also found that I need a way to `leave()` a particular topic when an archive is no longer in use.

Would a PR for that be welcome, too?

**Comment by dpaez** [comment]
Hi @RangerMauve. Oh yeah, that sounds right. 
Feel free to send your PR. I think #1 will be published pretty soon. Will let you know! Thanks.

**Comment by tinchoz49** [comment]
Hi @RangerMauve. Absolutely, any help is always welcome!

**Comment by tinchoz49** [comment]
https://github.com/geut/discovery-swarm-webrtc/pull/4
